import dns from "node:dns";
dns.setServers(['8.8.8.8', '8.8.4.4']);

import Footer from "@/components/shared/Footer";
import "./globals.css";
import 'animate.css';
import Navbar from "@/components/shared/Navbar";
import { Poppins } from 'next/font/google'
import { ToastContainer } from "react-toastify";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`h-full antialiased`}
      suppressHydrationWarning
    >
      <body className={`${poppins.className} min-h-full flex flex-col bg-[#F6F3F5]`}>
        <ToastContainer
          position="top-center"
          autoClose={3000} />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
